# Generated by Django 4.1.7 on 2024-03-11 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='correo',
            new_name='creditos',
        ),
    ]
